-- table tasks
CREATE TABLE tasks(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    responsable VARCHAR(200) NOT NULL,
    description VARCHAR(300),
    done BOOLEAN NOT NULL DEFAULT 0,
    creatAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
